### ISSUE TITLE
Uncaught TypeError: Cannot read property 'top' of undefined

### ISSUE THREAD

**Issue by trntv** [iserdmi/scrollport-js#5]
Возникает на scrollport.js:146
Для теста просто добавил data-scrollport анкорной ссылке. Судя по документации должно было сработать :-)

**Comment by trntv** [comment]
Извините, id побились на странице, но вообще, имхо, имеет смысл не крашиться при отсутствии на странице целевого элемента, а просто маякнуть в консоль.  Спасибо за плагин.

**Comment by iserdmi** [comment]
Здравствуйте. Спасибо за обратную связь. Сделаю со следующим обновлением.
