### ISSUE TITLE
Отличный плагин!

### ISSUE THREAD

**Issue by tarampampam** [iserdmi/scrollport-js#6]
Друже, ещё раз скажу тебе спасибо за отличный плагин. Дважды апнуть карму на хабре - увы, нельзя, хотя работа этого заслуживает.

Единственное но - может добавишь проверку на `typeof obj === 'object'` для первого аргумента?
Иначе при вызоове:

``` javascript
jQuery.scrollport(obj, {mode: 'roll', speed: 500});
```

Будет резонная но не совсем очевидная ошибка о невозможности обращения к свойству `.top`

**Comment by iserdmi** [comment]
Спасибо за добрые слова. Сейчас очень мало времени, позже сделаю.
